language: node_js
node_js:
- '13.5'
dist: trusty
sudo: false
branches:
  only:
  - master
before_script:
- npm install -g firebase-tools
- npm install -g @angular/cli
cache:
  directories:
  - node_modules
install:
- npm install
script:
- ng test --silent --no-stack-trace --ci
- ng build --prod --aot
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
env:
  global:
  - secure: ZUK7b6bOC516yjJBeFG2Um03HGufWxScZlvdp2QyAIMoR7frvOQntD2N7twDxL+RDS0RlKAxGNYtttG0I+G4joiek3ch2JeDa9fqcN9IWTWEBEd9n1juO9PseSIsC3t55h+a9GBahxXhg1rB9Xsux148s54pJDAmPRSTQDLIuU59wYL47KtRjjezczOM+F73ABvdgFJiBG+iycJKsFkN0WZFa+hDwrDvaek740AxIxLGqFSLoE2EufovoqbDImxwaOxbyT0V9u7sSTKZyoJ9vD12gijmmyBtAyiKX4rgZ3klnmaiR9JKuAgN+KvNuFKE9coBAre3RJVW4VRBuH8dHTiWMWYWOIUgXJeXH7/2NaWWiRfB1UZKvHQeidKnoFm+pfuyN7R05xzCOXxVm56OGCl7urPk8CBIr6T3uWqByn8q8yawn+wpv6Srzpq390lIrhCnFrll+qGGpGMYHxFZQhySnUYGHj6+8Lp1/39d4CbUpSLGpzT2/E6+HPEWkWf7/+5N2zZ0ArcWEOvMOfSrXX8r6PPMW3DGdXwNDfEqDyyymr64qdN1dc/eq3W2BL2LG+jodSG3i2MhTOPO3wd5OoSISjaLXI9euwvjwP1WGv4KEuzS5p/O+Z95nUYWUxZ6M0PF4yijRIkn6Wb907IRmNxiYpRraXFNvJ9FDJqlnBw=
