language: node_js
node_js:
  - "13.5"
dist: trusty
sudo: false

branches:
  only:
  - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

cache:
  directories:
  - node_modules

install:
  - npm install

script:
  # - npm run lint
  # - npm run test:headless
  # - xvfb-run npm run e2e
  # - ng test --watch=false --progress=false --browsers=ChromeHeadlessCI
  # - ng e2e --protractor-config=./e2e/protractor-ci.conf.js
  - ng build --prod --aot

deploy:
  provider: firebase
  token:
    secure: HnaCwxjKGWqoGarywEQ5kAeAywUPz6tGgRvbDqvyHhOOPSusuDgT1krzLwkI9NpGqoIEts4HytZDR7FY9riceMZAVSImN3XdadGvNkaMrbCtW1RxZQrGDCEzlfZSaVgwtTOycMVa56CIeuypnfaCOK3vFBwd44soShChW59rt4yV5LwEQxqIhWJNFSekW5N9/smRAGo5PiVfCZnsuYedtHOUHlNPwuLx/D8C89Royz2SqTgrb6wAnAJzdj9CuSgBp1lUXs3Z0aMweb8qaCGnRHMfH5uGhpZg2XO9hBEtld3tc00iPXskfuVWhncxondVDxcy9yncaWnehGnfWIqkCeKq9rbwiVweZ6PjTfhdmVv1TXhpBvOaTDBM3zSkJ7ESeVF3WJuzUA0AqFmtOCu+sa9n54cjl/Oy0YwxAFvQzOGaZjrN7465/Q7DHc003SYtrgCHC1PskziHuDLQ0v/bI4VSrA343R1D8uyWBhpqwvcC3DvnUvopzGPY//cBji6OtWVfhMz2ytKaVDu8E0yFUIJazQZCUgJFiZnjCm+lfqE2+7hY4W58yF/o7RrvatEDTehsXmneR3OhGaJxyJisfZGReO/wq8hcMCMF+8dITkbKrrilbfmMyRRsnhgZhFenCs48UA4RyMqjoalESVqMtg+wHW/5x+vCJTPloo1KDfs=
